### ISSUE TITLE
Display club executive roles in the member list

### ISSUE THREAD

**Issue by ChristopherWMM** [MCC-CSClub/mcc-csclub.github.io#35]
Currently, the member list displays various pieces of information if an attribute is present within a members markdown file (`*.md`) in the `/_members` folder. It would be a nice enhancement to display the club executives roles above their bio's using an optional `role` attribute like so:

----

![role](https://i.imgur.com/v5WuEyV.png)

```yml
---
name: Christopher Martin
role: President
short_bio: Full-time Computer Science student and budding Computer Science educator. 😁
image_url: https://avatars0.githubusercontent.com/u/9260792?s=460&v=4
website: https://christopherwmm.github.io/
github: ChristopherWMM
discord: ChristopherWMM#0458
---
```

----

Additionally, the member list could be pre-sorted to ensure that the officers are always displayed first with the following precedence: President, Vice-President, ICC Rep, Secretary, Treasurer, Project Manager, Event Coordinator, Social Media Manager. However, this could be done later on as a seperate enhancement.
